export default {
    AUTH:{
        LOGIN_STATUS_CHANGED:'AUTH_LOGIN_STATUS_CHANGED',
        TOKEN_EXPIRED:'AUTH_TOKEN_EXPIRED'
    },
    COMMENT:{
        CREATED:'COMMENT_CREATED'
    },
    OPINION:{
        CREATED:'OPINION_CREATED'
    },
    TOAST:{
        NEW_MESSAGE:'TOAST_NEW_MESSAGE'
    },
    ROUTER:{
        REDIRECT:'ROUTER_REDIRECT'
    }
}